### ISSUE TITLE
Pre-commit results in 'circular dependency' error

### ISSUE THREAD

**Issue by saifhassanctc** [dadav/helm-schema#10]
Any idea why I may see this error?

**.pre-commit-config.yaml**
```
- repo: https://github.com/dadav/helm-schema
    rev: 0.8.0
    hooks:
      - id: helm-schema
        args: [--log-level, "debug", --no-dependencies]
```

**chart.yaml** 
**Note**: 'env-metadata' chart doesn't have any depdencies
```
dependencies:
  - name: env-metadata
    version: "0.1.1"
```

**Error**
`ERRO[2023-10-31T14:34:10-05:00] Error while sorting results: Circular or missing dependency found`
