### ISSUE TITLE
additionalProperties: {schema} vs. annotated properties

### ISSUE THREAD

**Issue by TomasBahnik** [dadav/helm-schema#106]
Hello, I am facing an issue how to generate schema allowing validation of collection of named sub-objects. 

Example:
Let's say my annotated values.yaml file looks like this

```
# @schema
# required: true
# @schema
people:
  # @schema
  # required: true
  # type: integer
  # @schema
  weight: 100
  # @schema
  # required: true
  # type: integer
  # @schema
  height: 200
```

And I would like to generate schema that validates as correct the values

```
people:
  john:
    weight: 10
    height: 100
  mary:
    weight: 10
    height: 100
 ```
 
 but that validation fails. It validates as correct single person like `john.yaml`
 
 ```
 people:
  weight: 10
  height: 100
```
 
 The only way is to annotate the values.yaml file with additionalProperties: {schema} like 
 
 ```
# @schema
# additionalProperties: {
#        "properties": {
#          "height": {
#            "default": 100,
#            "description": "The height of the person in unspecified units.",
#            "title": "height",
#            "type": "integer"
#          },
#          "weight": {
#            "default": 10,
#            "description": "The weight of the person in unspecified units.",
#            "title": "weight",
#            "type": "integer"
#          }
#        },
#        "required": [
#          "weight",
#          "height"
#        ]
#      }
# required: true
# @schema
people:
  weight: 100
  height: 200
```
Which generates duplicated schema code.

The first question is whether I can achieve  validation of collection of named sub-objects without additionalProperties: {schema} annotattion i.e. only annotating individual properties in values file.

And second question. Is the $ref supposed to work also for additionalProperties like 

```
# additionalProperties: { $ref: people.json#/properties }
```

Thank you

Tomas
