### ISSUE TITLE
Redundant required: [] keys for types other than array

### ISSUE THREAD

**Issue by thiagowfx** [dadav/helm-schema#136]
Consider `values.yaml`:

```yaml
# yaml-language-server: $schema=values.schema.json

# -- Whether to enable vault
vault_enabled: false
```

When running `helm schema` via `pre-commit`:

```yaml
repos:
  - repo: https://github.com/dadav/helm-schema
    rev: 0.18.1
    hooks:
      - id: helm-schema
        args:
          - --add-schema-reference
          - --append-newline # Necessary to play well with end-of-file-fixer
          - --chart-search-root=helm
          - --no-dependencies
          - --skip-auto-generation=title
```

We get `values.schema.json`:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "global": {
      "description": "Global values are values that can be accessed from any chart or subchart by exactly the same name.",
      "required": [],
      "type": "object"
    },
    "vault_enabled": {
      "default": false,
      "description": "Whether to enable vault",
      "required": [],
      "type": "boolean"
    }
  },
  "required": [
    "vault_enabled"
  ],
  "type": "object"
}
```

Observed: `"required": []` entries.

Expected: There should be no `"required": []` entries. They serve no purpose for types other than `array` (such as `boolean` above for `vault_enabled`).
