### ISSUE TITLE
Schema for aliased chart dependency generated without alias

### ISSUE THREAD

**Issue by MIJOTHY-V2** [dadav/helm-schema#34]
Chart dependencies specified with an [alias](https://helm.sh/docs/topics/charts/#alias-field-in-dependencies) field have their schema generated under the dependency `name` rather than the `alias`.

`Chart.yaml`
```yaml
apiVersion: v2
description: Example umbrella chart
type: application
name: example-umbrella-chart
version: "0.0.1"
maintainers:
  - name: Someone
    email: someone@someplace.com
dependencies: 
- name: node-problem-detector
  alias: dep-a
  repository: https://charts.deliveryhero.io
  version: "2.3.11"
```

`values.yaml`
```yaml
dep-a:
  foo: bar
```

Generated Schema
```json
{
  "additionalProperties": false,
  "properties": {
    "dep-a": {
      "additionalProperties": false,
      "properties": {
        "foo": {
          "default": "bar",
          "title": "foo",
          "type": "string"
        }
      },
      "title": "dep-a",
      "type": "object",
      "required": [
        "foo"
      ]
    },
    "global": {
      "description": "Global values are values that can be accessed from any chart or subchart by exactly the same name.",
      "title": "global",
      "type": "object"
    },
    "node-problem-detector": {
      "properties": {
        "affinity": {
          "additionalProperties": false,
          "title": "affinity",
          "type": "object"
        },
...
```

Possibly simplest to just inline the schema under the alias, but another one could be that aliased dependencies become properties with `$ref`s to a `$def` of the underlying dependency, like

```json
{
  "additionalProperties": false,
  "properties": {
    "dep-a": {
      "$ref": "#/$defs/node-problem-detector",  
      "title": "dep-a"
    }
  },
  "$defs": {
    "node-problem-detector": {
      "additionalProperties": false,
      "properties": {
        "affinity": {
          "additionalProperties": false,
          "title": "affinity",
          "type": "object"
        }
      }
    }
  }
}
```

so the supplied `values.yaml` file of `dep-a: { foo: bar }` would be invalid here. 

Possibly relates to https://github.com/dadav/helm-schema/pull/30
